services:
  jenkins-controller:
    image: jenkins/jenkins:lts
    container_name: jenkins-controller
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./keys/jenkins-ssh-idrsa:/var/jenkins_home/.ssh/id_rsa:ro
      - ./keys/jenkins-ssh-idrsa.pub:/var/jenkins_home/.ssh/id_rsa.pub:ro
    networks:
      - jenkins

  jenkins-agent-base:
    build: 
      context: ./agent-base
    # volumes:
    #   - ./keys/jenkins-ssh-idrsa.pub:/home/jenkins/.ssh/authorized_keys:ro
    image: jenkins-agent-base
    command: /bin/true

  jenkins-agent:
    build: 
      context: ./agent-1
    container_name: jenkins-agent
    networks:
      - jenkins
    expose:
      - "22"
    volumes:
      - ./agent-1-vol:/workspace
    command: ["/usr/sbin/sshd", "-D"]

  

volumes:
  jenkins_home:

networks:
  jenkins:
